
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c18fc49177d85984dce3
            client-secret: 1718e0071f0c465bcd4be7d521e9e4c77a36f72c
          google:
            client-id: 453817235236-bo5n5vlh0d3hjvi42flpglp4m8bcje4h.apps.googleusercontent.com
            client-secret: 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
            

#logging:
#  level:
#    org.springframework.security: DEBUG

